### PR TITLE
2750 fix kafka tracker shutdown

### PR DESCRIPTION
**Pull request by akaspin**
[trello](https://trello.com/c/4Vjz3LQS)

### CODE REVIEW

**Comment by itszootime** [comment]
Are we sure this is the reason the shutdown is blocked? If you run main/tracker.go from master, it shuts down without any problems. The [errors channel will be closed on the call to `fast.Close()`](https://github.com/remerge/sarama/blob/d7de19a9cb61cc9eee8e8baae5f8902ee9783837/async_producer.go#L838), then the `for` channel receive loop should exit. Or am I missing something?

**Comment by akaspin** [comment]
@itszootime `asyncProducer` closes error channel and `range` should exit. This behaviour was implemented. Hmm. Sec.

**Comment by dynamix** [comment]
if this isn't the reason / fix, lets not add this extra logic. @akaspin @itszootime

**Comment by itszootime** [comment]
Seems like this isn't an issue then @akaspin, I'll close this PR.

**Comment by akaspin** [comment]
@itszootime 👍

**Pull request closed without merging**
